# Generated by Django 5.1.4 on 2024-12-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_joined_customuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
