# Generated by Django 5.1.4 on 2024-12-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_date_joined_customuser_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='join_date',
            new_name='date_joined',
        ),
    ]
