# Generated by Django 5.1.4 on 2024-12-17 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('ship_date', models.DateField(default=django.utils.timezone.now)),
                ('order_priority', models.CharField(choices=[('H', 'H'), ('M', 'M'), ('L', 'L'), ('C', 'C')], default='L', max_length=5)),
                ('sales_channel', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('item_type', 'unit_price', 'unit_cost')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv_file.region')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sold', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv_file.country')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv_file.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv_file.product')),
            ],
        ),
    ]
