# Generated by Django 5.1.4 on 2024-12-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv_file', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='upload_csv__name_aa216b_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='upload_csv__region__50565d_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at'], name='upload_csv__uploade_1802cd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='upload_csv__order_i_e9240c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='upload_csv__order_d_fba993_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ship_date'], name='upload_csv__ship_da_738ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_priority'], name='upload_csv__order_p_f8753a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sales_channel'], name='upload_csv__sales_c_53665a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_type'], name='upload_csv__item_ty_803c83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_price'], name='upload_csv__unit_pr_fb8368_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_cost'], name='upload_csv__unit_co_fd7fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='upload_csv__name_ddb7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['order'], name='upload_csv__order_i_cd2de2_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['country'], name='upload_csv__country_072cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['product'], name='upload_csv__product_ae0ac6_idx'),
        ),
    ]
