# Generated by Django 5.1.4 on 2024-12-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv_file', '0006_order_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
