# Generated by Django 5.1.4 on 2024-12-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv_file', '0007_order_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delete',
        ),
    ]
